storage: ./storage

listen:
  - 0.0.0.0:80

middlewares:
  gitlab-oauth:
    enabled: true

auth:
  gitlab-oauth:
    group: <group>
    client-id: <client_id>
    client-secret: <client_secret>
    gitlab-host: https://git.geektr.co

web:
  enable: true
  title: GNPM
  # logo: gnpm.png
  scope: \@geektr-local

uplinks:
  npmjs:
    url: http://registry.npm.taobao.org/
    cache: false

packages:
  '@geektr-local/*':
    access: $all
    publish: $authenticated
  '@geektr-private/*':
    access: $authenticated
    publish: $authenticated
  '**':
    access: $all
    publish: $authenticated
    proxy: npmjs

logs:
  - {type: stdout, format: pretty, level: http}
